### PR TITLE
Enhance export

### LINKED ISSUE #17: PDF does not generate
## Issue

PDF Export Module is installed in Icinga so I can download SLA reports.
The binary is pointed to /usr/bin/google-chrome-stable.

When clicking the **Download** > **PDF** link in Icinga a new tab opens but nothing further happens (no PDF is generated or downloads, tab header just says 'Loading...' but never completes).

## Expected Behavior

I would expect the PDF to be generated and download in Chrome.
Generating a CSV or JSON works OK without issue.

## Current Behavior

When clicking the **Download** > **PDF** link in Icinga a new tab opens but nothing further happens (no PDF is generated or downloads, tab header just says 'Loading...' but never completes).

On the server side I can see active processes, which never complete and remain open unless killed manually:

`ps aux | grep chrome`

`www-data  5127  0.0  0.0   4276   740 ?        S    12:23   0:00 sh -c '/usr/bin/google-chrome-stable' '--headless' '--disable-gpu' '--no-sandbox' '--remote-debugging-port=0'`

`www-data  5128  0.3  3.5 534056 72384 ?        Sl   12:23   0:00 /usr/bin/google-chrome-stable --headless --disable-gpu --no-sandbox --remote-debugging-port=0`

`www-data  5141  0.1  2.2 400492 45740 ?        S    12:23   0:00 /opt/google/chrome/chrome --type=zygote --no-sandbox --headless --headless --enable-crash-reporter`

`www-data  5155  0.1  3.1 442484 64524 ?        Sl   12:23   0:00 /opt/google/chrome/chrome --type=gpu-process --field-trial-handle=409458055811527330,9041078600582879043,131072 --no-sandbox --headless --headless --enable-crash-reporter --gpu-preferences=KAAAAAAAAAAgAAAgAAAAAAAAYAAAAAAAEAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAA --use-gl=swiftshader-webgl --override-use-software-gl-for-tests --service-request-channel-token=10587834501044168516`

`www-data  5156  0.1  2.4 449796 50908 ?        Sl   12:23   0:00 /opt/google/chrome/chrome --type=utility --field-trial-handle=409458055811527330,9041078600582879043,131072 --lang=en-US --service-sandbox-type=network --no-sandbox --use-gl=swiftshader-webgl --headless --enable-crash-reporter --service-request-channel-token=7961077103313469533 --shared-files=v8_context_snapshot_data:100,v8_natives_data:101`

`www-data  5159  0.1  3.0 623100 62192 ?        Sl   12:23   0:00 /opt/google/chrome/chrome --type=renderer --no-sandbox --allow-pre-commit-input --use-gl=swiftshader-webgl --field-trial-handle=409458055811527330,9041078600582879043,131072 --disable-databases --disable-gpu-compositing --lang=en-US --headless --enable-crash-reporter --num-raster-threads=1 --service-request-channel-token=7049592006485112464 --renderer-client-id=4 --shared-files=v8_context_snapshot_data:100,v8_natives_data:101`

## Your Environment
* Icinga Web 2 Version: 2.7.3
* PHP Version: 5.6.40-0+deb8u5
* Icinga 2 version: r2.10.5-1
* PDF Export Module version: 0.9.1
* Dependent module versions: idoreports (0.9.1), reporting (0.10.0), ipl (0.4.0), reactbundle (0.7.0)
* Operating System and version: Debian GNU/Linux 9.11 (stretch)
* Webserver version: Apache/2.4.25 (Debian)

### PR DESCRIPTION
**Pull request by nilmerg**
* Avoids disk storage entirely now.
* Fixes zombie processes on Linux.
* Prevents errors and warnings which were cluttering up the output.
* Ensures that users get a proper error message in case generation fails.

fixes #17

### CODE REVIEW

**Comment by cristorrian** [comment]
Thanks @nilmerg for the fix. :+1: 
With this fix and the patch of @durzo the pdfexport module work properly.
But the pdf file sent trought job schedule of reporting module is sent on plain text without red and green buubles.
I think that this issue is related with the reporting module.

I have posted this issue here:
https://github.com/Icinga/icingaweb2-module-reporting/issues/47

**Comment by netphantm** [comment]
It works nice w/ php7.3, but in php7.4 it still hangs and you'll get this in the browser window:
```
Empty read; connection dead? Stream state: {"timed_out":false,"blocked":true,"eof":true,"stream_type":"tcp_socket\/ssl","mode":"r+","unread_bytes":0,"seekable":false}
```
and this (from the icingaweb2.log):
```
2020-02-24T14:08:29+01:00 - ERROR - Terminated browser process after 10 seconds elapsed without the expected output
2020-02-24T14:08:31+01:00 - ERROR - WebSocket\ConnectionException in /usr/share/icingaweb2/modules/pdfexport/vendor/textalk/websocket/lib/Base.php:202 with message: Empty read; connection dead?  Stream state: {"timed_out":false,"blocked":true,"eof":true,"stream_type":"tcp_socket\/ssl","mode":"r+","unread_bytes":0,"seekable":false}
#0 /usr/share/icingaweb2/modules/pdfexport/vendor/textalk/websocket/lib/Base.php(92): WebSocket\Base->read()
#1 /usr/share/icingaweb2/modules/pdfexport/vendor/textalk/websocket/lib/Base.php(173): WebSocket\Base->receive()
#2 /usr/share/icingaweb2/modules/pdfexport/library/Pdfexport/HeadlessChrome.php(314): WebSocket\Base->close()
#3 /usr/share/icingaweb2/modules/pdfexport/library/Pdfexport/HeadlessChrome.php(235): Icinga\Module\Pdfexport\HeadlessChrome->printToPDF()
#4 /usr/share/icingaweb2/modules/reactbundle/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(70): Icinga\Module\Pdfexport\HeadlessChrome->Icinga\Module\Pdfexport\{closure}()
#5 /usr/share/icingaweb2/modules/reactbundle/vendor/react/stream/src/ReadableResourceStream.php(146): Evenement\EventEmitter->emit()
#6 /usr/share/icingaweb2/modules/reactbundle/vendor/react/event-loop/src/StreamSelectLoop.php(244): React\Stream\ReadableResourceStream->handleData()
#7 /usr/share/icingaweb2/modules/reactbundle/vendor/react/event-loop/src/StreamSelectLoop.php(211): React\EventLoop\StreamSelectLoop->waitForStreamActivity()
#8 /usr/share/icingaweb2/modules/pdfexport/library/Pdfexport/HeadlessChrome.php(245): React\EventLoop\StreamSelectLoop->run()
#9 /usr/share/icingaweb2/modules/pdfexport/library/Pdfexport/ProvidedHook/Pdfexport.php(87): Icinga\Module\Pdfexport\HeadlessChrome->toPdf()
#10 /usr/share/icingaweb2/modules/reporting/application/controllers/ReportController.php(118): Icinga\Module\Pdfexport\ProvidedHook\Pdfexport->streamPdfFromHtml()
#11 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Reporting\Controllers\ReportController->downloadAction()
#12 /usr/share/icingaweb2/library/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch()
#13 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch()
#14 /usr/share/icingaweb2/library/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch()
#15 /usr/share/icingaweb2/library/Icinga/Application/webrouter.php(99): Icinga\Application\Web->dispatch()
#16 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#17 {main}
```

**Comment by nilmerg** [comment]
@netphantm Could you please run the following manually on the host with PHP 7.4?

`HOME=/tmp /usr/local/bin/google-chrome --bwsi --headless --disable-gpu --no-sandbox --no-first-run --disable-dev-shm-usage --remote-debugging-port=0 --homedir=/tmp --user-data-dir=/tmp`

or turn on DEBUG logging for icingaweb2.

Either way, the actual output of the browser should be visible. Please include that in your reply.

**Comment by netphantm** [comment]
hmm, I had to try it a few times, since it suddenly worked sometimes, until it didn't
and here it is:
```2020-02-24T14:30:32+01:00 - DEBUG - Starting browser process: HOME=/tmp/5e53cff8eea22/HOME exec '/usr/bin/chromium-browser' '--bwsi' '--headless' '--disable-gpu' '--no-sandbox' '--no-first-run' '--disable-dev-shm-usage' '--remote-debugging-port=0' '--homedir=''/tmp/5e53cff8eea22/HOME' '--user-data-dir=''/tmp/5e53cff8eea22/HOME'
2020-02-24T14:30:33+01:00 - DEBUG - Caught browser output: 
DevTools listening on ws://127.0.0.1:39011/devtools/browser/4bcc3df0-1063-4251-a880-73bb2e895599

2020-02-24T14:30:33+01:00 - DEBUG - Transmitting CDP call: Target.createTarget(url)
2020-02-24T14:30:33+01:00 - DEBUG - Received CDP result: targetId
2020-02-24T14:30:33+01:00 - DEBUG - Transmitting CDP call: Page.enable()
2020-02-24T14:30:33+01:00 - DEBUG - Received CDP result: none
2020-02-24T14:30:33+01:00 - DEBUG - Transmitting CDP call: Page.navigate(url)
2020-02-24T14:30:33+01:00 - DEBUG - Received CDP result: frameId,loaderId
2020-02-24T14:30:33+01:00 - DEBUG - Awaiting CDP event: Page.frameStoppedLoading(frameId)
2020-02-24T14:30:33+01:00 - DEBUG - Received CDP event: Page.frameStartedLoading(frameId)
2020-02-24T14:30:33+01:00 - DEBUG - Received CDP event: Page.frameNavigated(frame)
2020-02-24T14:30:33+01:00 - DEBUG - Received CDP event: Page.domContentEventFired(timestamp)
2020-02-24T14:30:33+01:00 - DEBUG - Received CDP event: Page.loadEventFired(timestamp)
2020-02-24T14:30:33+01:00 - DEBUG - Received CDP event: Page.frameStoppedLoading(frameId)
2020-02-24T14:30:33+01:00 - DEBUG - Transmitting CDP call: Page.printToPDF(headerTemplate,displayHeaderFooter,footerTemplate,transferMode,printBackground)
2020-02-24T14:30:33+01:00 - DEBUG - Received CDP event: Page.frameResized()
2020-02-24T14:30:33+01:00 - DEBUG - Received CDP event: Page.frameResized()
2020-02-24T14:30:34+01:00 - DEBUG - Received CDP result: data
2020-02-24T14:30:34+01:00 - ERROR - WebSocket\ConnectionException in /usr/share/icingaweb2/modules/pdfexport/vendor/textalk/websocket/lib/Base.php:202 with message: Empty read; connection dead?  Stream state: {"timed_out":false,"blocked":true,"eof":true,"stream_type":"tcp_socket\/ssl","mode":"r+","unread_bytes":0,"seekable":false}
#0 /usr/share/icingaweb2/modules/pdfexport/vendor/textalk/websocket/lib/Base.php(92): WebSocket\Base->read()
#1 /usr/share/icingaweb2/modules/pdfexport/vendor/textalk/websocket/lib/Base.php(173): WebSocket\Base->receive()
#2 /usr/share/icingaweb2/modules/pdfexport/library/Pdfexport/HeadlessChrome.php(314): WebSocket\Base->close()
#3 /usr/share/icingaweb2/modules/pdfexport/library/Pdfexport/HeadlessChrome.php(235): Icinga\Module\Pdfexport\HeadlessChrome->printToPDF()
#4 /usr/share/icingaweb2/modules/reactbundle/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(70): Icinga\Module\Pdfexport\HeadlessChrome->Icinga\Module\Pdfexport\{closure}()
#5 /usr/share/icingaweb2/modules/reactbundle/vendor/react/stream/src/ReadableResourceStream.php(146): Evenement\EventEmitter->emit()
#6 /usr/share/icingaweb2/modules/reactbundle/vendor/react/event-loop/src/StreamSelectLoop.php(244): React\Stream\ReadableResourceStream->handleData()
#7 /usr/share/icingaweb2/modules/reactbundle/vendor/react/event-loop/src/StreamSelectLoop.php(211): React\EventLoop\StreamSelectLoop->waitForStreamActivity()
#8 /usr/share/icingaweb2/modules/pdfexport/library/Pdfexport/HeadlessChrome.php(245): React\EventLoop\StreamSelectLoop->run()
#9 /usr/share/icingaweb2/modules/pdfexport/library/Pdfexport/ProvidedHook/Pdfexport.php(78): Icinga\Module\Pdfexport\HeadlessChrome->toPdf()
#10 /usr/share/icingaweb2/modules/reporting/application/controllers/ReportController.php(118): Icinga\Module\Pdfexport\ProvidedHook\Pdfexport->streamPdfFromHtml()
#11 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Reporting\Controllers\ReportController->downloadAction()
#12 /usr/share/icingaweb2/library/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch()
#13 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch()
#14 /usr/share/icingaweb2/library/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch()
#15 /usr/share/icingaweb2/library/Icinga/Application/webrouter.php(99): Icinga\Application\Web->dispatch()
#16 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#17 {main}
```

**Comment by nilmerg** [comment]
Hmmm, okay. Though this is different than what you initially posted. Please report back (again with the browser's output) in case the error is this: *Terminated browser process after 10 seconds elapsed without the expected output*

While the log you just posted is of course valuable it doesn't explain the error above.

**Comment by netphantm** [comment]
hm, I cannot get it to throw the same error again, it's this last one again and again (Empty read; connection dead?), and sometimes it just works.
I ran what you posted tho, perhaps this helps:

```www-data@hermes:~$ HOME=/tmp /usr/bin/chromium-browser  --bwsi --headless --disable-gpu --no-sandbox --no-first-run --disable-dev-shm-usage --remote-debugging-port=0 --homedir=/tmp --user-data-dir=/tmp

DevTools listening on ws://127.0.0.1:43339/devtools/browser/61a7484f-f2e1-463a-85e0-bd1d66887fed
[0224/153636.061778:ERROR:devtools_http_handler.cc(293)] Error writing DevTools active port to file
X11 connection rejected because of wrong authentication.
X11 connection rejected because of wrong authentication.
X11 connection rejected because of wrong authentication.
X11 connection rejected because of wrong authentication.
X11 connection rejected because of wrong authentication.
X11 connection rejected because of wrong authentication.
X11 connection rejected because of wrong authentication.
X11 connection rejected because of wrong authentication.
X11 connection rejected because of wrong authentication.
X11 connection rejected because of wrong authentication.
X11 connection rejected because of wrong authentication.
X11 connection rejected because of wrong authentication.
X11 connection rejected because of wrong authentication.
X11 connection rejected because of wrong authentication.
X11 connection rejected because of wrong authentication.
X11 connection rejected because of wrong authentication.
X11 connection rejected because of wrong authentication.
X11 connection rejected because of wrong authentication.
X11 connection rejected because of wrong authentication.
X11 connection rejected because of wrong authentication.
X11 connection rejected because of wrong authentication.
X11 connection rejected because of wrong authentication.
X11 connection rejected because of wrong authentication.
X11 connection rejected because of wrong authentication.
X11 connection rejected because of wrong authentication.
X11 connection rejected because of wrong authentication.
X11 connection rejected because of wrong authentication.
X11 connection rejected because of wrong authentication.
X11 connection rejected because of wrong authentication.
X11 connection rejected because of wrong authentication.
X11 connection rejected because of wrong authentication.
X11 connection rejected because of wrong authentication.
X11 connection rejected because of wrong authentication.
``` 
and there it hangs.

**Comment by nilmerg** [comment]
Yes this might be of help. Thanks!

**Comment by netphantm** [comment]
I noticed that on very rare occasions, it works even with php-7.4 on this system (Ubuntu 18.04.4 LTS, 4.14.150-170 armv7l, chromium).
On the company server (debian 10, 4.19.0-6-amd64 with php-7.3 and chrome) it works almost all the times (one user reported an error tho).
If I encounter another error, I will post it here.

**Pull request merged**
